# Test your FastAPI endpoints

GET http://127.0.0.1:8000/Data/Read/
Accept: application/json

###

POST https://127.0.0.1:8000/Data/Create/
Accept: application/json

###

PUT https://127.0.0.1:8000/Data/Update/
Accept: application/json

###

DELETE https://127.0.0.1:8000/Data/Delete/
Accept: application/json

###
